### ISSUE TITLE
Handlers don't seem to be registered with property injection

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.Extensions.DependencyInjection#18]
I'm probably doing something wrong here to enable property injection in my handlers, but the following doesn't inject properties. I've tried using the provider factory but I will need access to the final container/scope. 

![image](https://user-images.githubusercontent.com/383634/75660994-cdf79680-5c6c-11ea-9481-6c76eb1f06c0.png)

**Comment by danielmarbach** [comment]
hi jan,

Property injection is not supported by the MS DI. If you want property injection you have to code it out similar to

https://stackoverflow.com/questions/57379247/property-injection-in-microsoft-extensions-dependencyinjection

see also

https://docs.particular.net/nservicebus/dependency-injection/extensions-dependencyinjection#property-injection

Hope that helps

**Comment by janpieterz** [comment]
@danielmarbach right, not by default, but there are ways to get it done when the container supports it without hard coding it out. 
For example an ASP.NET Core controller has property injection with Autofac as a service enabled. We never manually register the controllers. 

The only thing I can imagine is copying behavior from https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/develop/src/Autofac.Extensions.DependencyInjection/AutofacRegistration.cs to automatically populate everything from the service collection passed back by NServiceBus but it seems odd that it would be needed to break abstractions like that, compared to the defaults in ASP.NET Core.

**Comment by danielmarbach** [comment]
@janpieterz Quick question. Are you suggestion we should change something? Because right now

**Comment by danielmarbach** [comment]
@janpieterz I'm not an autofac expert. It does look like though autofac doesn't magically do property injection, not even for Aspnetcore, as defined in the documentation

![image](https://user-images.githubusercontent.com/174258/75788800-041a4080-5d69-11ea-92b3-2cb1ff5661bb.png)

https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#controllers-as-services

You can though enforce it by doing the following

```
class AutofacPropertyInjectionModule : Module
    {
        protected override void AttachToComponentRegistration(IComponentRegistryBuilder componentRegistry, IComponentRegistration registration)
        {
            registration.Activating += (sender, args) => args.Context.InjectProperties(args.Instance);
        }
    }

endpointConfiguration.UseContainer(new AutofacServiceProviderFactory(c => c.RegisterModule<AutofacPropertyInjectionModule>()));
```

or register it in your code and then it will work

I created a quick sample based on an existing one to demonstrate it

https://github.com/Particular/docs.particular.net/commit/d36e088733c577a1865a236b4b8cbac377483ac3

**Comment by janpieterz** [comment]
@danielmarbach apologies, don't know _what_ controller I was looking at this morning but it wasn't an ASP.NET Core one I think. Can't find it anywhere anymore. 
Way we do it is indeed via controller injection in core.

**Comment by danielmarbach** [comment]
@janpieterz perfect.

It does seem though due to MS pushing MS DI the .NET world as a whole is moving more and more away from property injection. Maybe worth considering that we will see across the board less and less support for it.
